### ISSUE TITLE
Add Unix support

### ISSUE THREAD

**Issue by Pedneri1** [Pedneri1/wifi_password#2]
The package is currently supporting only Darwin Unix, we should add support for others OS from the family.

**Comment by fcapovilla** [comment]
I'm using Linux, so I'll give this one a try.

**Comment by Pedneri1** [comment]
Thats great! I was heavily inspired by [this project](https://github.com/kevva/wifi-password). Maybe it will help you

**Comment by Pedneri1** [comment]
Done in #3
